FROM golang:1.22.3-alpine3.20 as builder
WORKDIR /app
COPY . .
RUN CGO_ENABLED=0 GOOS=linux \
    go build \
    -o cloud_run main.go

FROM alpine:3.20
WORKDIR /app
COPY --from=builder /app/cloud_run .
COPY .env .
ENTRYPOINT [ "./cloud_run" ]
